<template>
  <PageHeader title="商户角色" description="管理本商户内的角色与权限配置。商户管理员只能配置本商户范围内的权限，不能授予平台权限。" eyebrow="权限管理"><template #action><el-button type="primary" @click="openCreate">新增角色</el-button></template></PageHeader>
  <el-alert title="商户角色与平台角色属于不同权限域。" type="warning" :closable="false" show-icon class="merchant-notice" />
  <InkCard v-loading="loading"><el-table :data="roles" class="data-table"><el-table-column prop="name" label="角色名称" min-width="160" /><el-table-column prop="roleCode" label="角色标识" min-width="180"><template #default="{ row }"><code>{{ row.roleCode }}</code></template></el-table-column><el-table-column prop="description" label="角色说明" min-width="220" /><el-table-column label="系统角色" width="100"><template #default="{ row }"><el-tag :type="row.systemRole ? 'warning' : 'info'">{{ row.systemRole ? '是' : '否' }}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="row.status === 'ENABLED' ? 'success' : 'info'">{{ row.status === 'ENABLED' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="240" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="configure(row)">配置权限</el-button><el-button v-if="!row.systemRole" link @click="openEdit(row)">编辑</el-button><el-button v-if="!row.systemRole" link :type="row.status === 'ENABLED' ? 'danger' : 'primary'" @click="toggle(row)">{{ row.status === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></InkCard>
  <el-dialog v-model="dialogVisible" :title="editing ? '编辑商户角色' : '新增商户角色'" width="500px"><el-form label-width="82px"><el-form-item v-if="!editing" label="角色标识"><el-input v-model="form.roleCode" placeholder="merchant_operator" /></el-form-item><el-form-item label="角色名称"><el-input v-model="form.name" /></el-form-item><el-form-item label="角色说明"><el-input v-model="form.description" type="textarea" :rows="3" /></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" @click="save">保存角色</el-button></template></el-dialog>
  <el-dialog v-model="permissionVisible" title="配置商户角色权限" width="650px"><el-checkbox-group v-model="selectedPermissionIds" class="permission-list"><el-checkbox v-for="permission in permissions" :key="permission.id" :value="permission.id">{{ permission.name }}（{{ permission.permissionCode }}）</el-checkbox></el-checkbox-group><template #footer><el-button @click="permissionVisible=false">取消</el-button><el-button type="primary" @click="savePermissions">保存权限</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import PageHeader from '../../components/common/PageHeader.vue'; import InkCard from '../../components/common/InkCard.vue'; import { message } from '../../utils/message'
import { createMerchantRole, listMerchantPermissions, listMerchantRolePermissionIds, listMerchantRoles, updateMerchantRole, updateMerchantRolePermissionIds, updateMerchantRoleStatus, type MerchantPermission, type MerchantRole } from '../../api/merchant/infrastructure'
const roles = ref<MerchantRole[]>([]); const permissions = ref<MerchantPermission[]>([]); const loading = ref(false); const dialogVisible = ref(false); const permissionVisible = ref(false); const editing = ref(false); const currentRole = ref<MerchantRole>(); const selectedPermissionIds = ref<number[]>([]); const form = reactive({ roleCode: '', name: '', description: '' })
async function load() { loading.value = true; try { roles.value = await listMerchantRoles() } catch (error) { message.error(error instanceof Error ? error.message : '商户角色加载失败') } finally { loading.value = false } }
function openCreate() { editing.value = false; Object.assign(form, { roleCode: '', name: '', description: '' }); dialogVisible.value = true }
function openEdit(row: MerchantRole) { editing.value = true; Object.assign(form, { roleCode: row.roleCode, name: row.name, description: row.description ?? '' }); currentRole.value = row; dialogVisible.value = true }
async function save() { try { if (editing.value && currentRole.value) await updateMerchantRole(currentRole.value.id, { name: form.name, description: form.description }); else await createMerchantRole(form); dialogVisible.value = false; message.success('商户角色保存成功'); await load() } catch (error) { message.error(error instanceof Error ? error.message : '商户角色保存失败') } }
async function toggle(row: MerchantRole) { try { await updateMerchantRoleStatus(row.id, row.status === 'ENABLED' ? 'DISABLED' : 'ENABLED'); message.success('商户角色状态已更新'); await load() } catch (error) { message.error(error instanceof Error ? error.message : '商户角色状态更新失败') } }
async function configure(row: MerchantRole) { try { currentRole.value = row; permissions.value = await listMerchantPermissions(); selectedPermissionIds.value = await listMerchantRolePermissionIds(row.id); permissionVisible.value = true } catch (error) { message.error(error instanceof Error ? error.message : '角色权限加载失败') } }
async function savePermissions() { if (!currentRole.value) return; try { await updateMerchantRolePermissionIds(currentRole.value.id, selectedPermissionIds.value); permissionVisible.value = false; message.success('商户角色权限保存成功') } catch (error) { message.error(error instanceof Error ? error.message : '商户角色权限保存失败') } }
onMounted(load)
</script>
<style scoped>.merchant-notice{margin-bottom:18px}code{color:var(--domain-700);font:12px ui-monospace,Consolas,monospace}.permission-list{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:8px}.permission-list .el-checkbox{margin-right:0;white-space:normal;line-height:1.5}@media(max-width:600px){.permission-list{grid-template-columns:1fr}}</style>
