<template>
  <PageHeader title="员工账号" description="管理本商户范围内的员工账号。账号只能访问所属商户，平台账号与商户账号相互独立。" eyebrow="权限管理"><template #action><el-button type="primary" :icon="Plus" @click="openCreate">新增员工</el-button></template></PageHeader>
  <InkCard v-loading="loading"><div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索员工姓名或手机号" :prefix-icon="Search" /><el-select v-model="status" placeholder="账号状态" clearable><el-option label="启用" value="ENABLED" /><el-option label="停用" value="DISABLED" /></el-select></div><el-table :data="filteredStaff" class="data-table"><el-table-column prop="displayName" label="员工姓名" min-width="150" /><el-table-column prop="mobile" label="联系电话" min-width="140" /><el-table-column label="账号状态" min-width="100"><template #default="{ row }"><el-tag :type="row.status === 'ENABLED' ? 'success' : 'info'">{{ row.status === 'ENABLED' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column prop="id" label="账号编号" min-width="160" /><el-table-column label="操作" width="180" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="openEdit(row)">编辑</el-button><el-button link :type="row.status === 'ENABLED' ? 'danger' : 'primary'" @click="toggle(row)">{{ row.status === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table><div class="table-foot">共 {{ filteredStaff.length }} 名员工 · 数据范围：当前商户当前门店</div></InkCard>
  <el-dialog v-model="dialogVisible" :title="editing ? '编辑员工账号' : '新增员工'" width="500px"><el-form label-width="82px"><el-form-item label="姓名"><el-input v-model="form.displayName" /></el-form-item><el-form-item label="手机号"><el-input v-model="form.mobile" /></el-form-item><el-form-item v-if="!editing" label="初始密码"><el-input v-model="form.password" type="password" show-password /></el-form-item><el-form-item label="商户角色"><el-select v-model="form.roleId" style="width:100%"><el-option v-for="role in roles" :key="role.id" :label="role.name" :value="role.id" /></el-select></el-form-item></el-form><template #footer><el-button @click="dialogVisible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存员工</el-button></template></el-dialog>
</template>
<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { Plus, Search } from 'lucide-vue-next'
import PageHeader from '../../components/common/PageHeader.vue'
import InkCard from '../../components/common/InkCard.vue'
import { message } from '../../utils/message'
import { createMerchantStaff, listMerchantRoles, listMerchantStaff, updateMerchantStaff, updateMerchantStaffStatus, type MerchantRole, type MerchantStaff } from '../../api/merchant/infrastructure'
const keyword = ref(''); const status = ref(''); const loading = ref(false)
const saving = ref(false); const dialogVisible = ref(false); const editing = ref(false); const currentStaff = ref<MerchantStaff>(); const staff = ref<MerchantStaff[]>([]); const roles = ref<MerchantRole[]>([])
const form = reactive({ displayName: '', mobile: '', password: '', roleId: 0 })
const filteredStaff = computed(() => staff.value.filter(item => (!keyword.value || `${item.displayName}${item.mobile}`.includes(keyword.value)) && (!status.value || item.status === status.value)))
async function load() { loading.value = true; try { [staff.value, roles.value] = await Promise.all([listMerchantStaff(), listMerchantRoles()]) } catch (error) { message.error(error instanceof Error ? error.message : '员工账号加载失败') } finally { loading.value = false } }
function openCreate() { editing.value = false; currentStaff.value = undefined; Object.assign(form, { displayName: '', mobile: '', password: '', roleId: roles.value[0]?.id ?? 0 }); dialogVisible.value = true }
function openEdit(row: MerchantStaff) { editing.value = true; currentStaff.value = row; Object.assign(form, { displayName: row.displayName, mobile: row.mobile, password: '', roleId: roles.value[0]?.id ?? 0 }); dialogVisible.value = true }
async function save() { if (!form.roleId) { message.warning('请选择商户角色'); return } saving.value = true; try { if (editing.value && currentStaff.value) await updateMerchantStaff(currentStaff.value.id, { displayName: form.displayName, mobile: form.mobile, roleId: form.roleId }); else await createMerchantStaff({ displayName: form.displayName, mobile: form.mobile, password: form.password, roleId: form.roleId }); dialogVisible.value = false; message.success('员工账号保存成功'); await load() } catch (error) { message.error(error instanceof Error ? error.message : '员工账号保存失败') } finally { saving.value = false } }
async function toggle(row: MerchantStaff) { try { await updateMerchantStaffStatus(row.id, row.status === 'ENABLED' ? 'DISABLED' : 'ENABLED'); message.success('员工账号状态已更新'); await load() } catch (error) { message.error(error instanceof Error ? error.message : '员工账号状态更新失败') } }
onMounted(load)
</script>
<style scoped>.toolbar{display:flex;gap:10px;padding:18px 20px;border-bottom:1px solid #ebeef1}.toolbar .el-input{max-width:320px}.toolbar .el-select{width:150px}.table-foot{padding:14px 20px;color:#8e8e90;font-size:12px;border-top:1px solid #ebeef1}@media(max-width:560px){.toolbar{flex-direction:column}.toolbar .el-input,.toolbar .el-select{max-width:none;width:100%}}</style>
