<template>
  <PageHeader title="平台角色" description="配置平台职责角色和权限范围；预设角色和自定义角色均可按授权规则维护。" eyebrow="权限管理"><template #action><el-button type="primary" @click="openCreate">新增角色</el-button></template></PageHeader>
  <div class="info-banner">平台角色仅适用于平台管理端；商户后台使用独立的角色与权限域，两者不能混用。</div>
  <section class="content-card"><div class="table-summary"><div>共 <b>{{ filteredRoles.length }}</b> 条记录</div><div class="table-summary-filter"><el-input v-model="keyword" :prefix-icon="Search" clearable placeholder="搜索角色名称或标识" /><el-button :icon="RefreshCw" circle :loading="loading" aria-label="刷新列表" @click="load" /></div></div><el-table v-loading="loading" :data="filteredRoles" class="data-table" empty-text="暂无平台角色"><el-table-column label="角色名称" min-width="160"><template #default="{ row }"><b class="primary-cell">{{ row.name }}</b></template></el-table-column><el-table-column label="角色标识" min-width="230"><template #default="{ row }"><code>{{ row.roleCode }}</code></template></el-table-column><el-table-column prop="description" label="角色说明" min-width="260" show-overflow-tooltip /><el-table-column label="角色类型" width="120"><template #default="{ row }"><el-tag class="role-kind" :class="row.systemRole ? 'role-system' : 'role-custom'">{{ row.systemRole ? '系统预置' : '自定义' }}</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag class="status-tag" :class="row.status === 'ENABLED' ? 'status-enabled' : 'status-disabled'">{{ row.status === 'ENABLED' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="操作" width="250" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="managePermissions(row)">配置权限</el-button><el-button link @click="openEdit(row)">编辑</el-button><el-button link :type="row.status === 'ENABLED' ? 'danger' : 'primary'" @click="toggleStatus(row)">{{ row.status === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></section>
  <RoleFormDialog v-model="dialogVisible" :role="editingRole" :submitting="saving" @submit="save" />
  <RolePermissionDialog v-model="permissionDialogVisible" :role="permissionRole" :permissions="permissions" :permission-ids="selectedPermissionIds" :saving="savingPermissions" @save="savePermissions" />
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { RefreshCw, Search } from 'lucide-vue-next'
import PageHeader from '../../components/common/PageHeader.vue'
import RoleFormDialog from '../../components/business/platform/RoleFormDialog.vue'
import RolePermissionDialog from '../../components/business/platform/RolePermissionDialog.vue'
import { createPlatformRole, listPlatformPermissions, listPlatformRolePermissionIds, listPlatformRoles, replacePlatformRolePermissions, updatePlatformRole, updatePlatformRoleStatus } from '../../api/platform/access'
import type { PlatformPermission, PlatformRole, PlatformRoleCommand, UpdatePlatformRoleCommand } from '../../types/platform-access'

const roles = ref<PlatformRole[]>([]); const permissions = ref<PlatformPermission[]>([]); const loading = ref(false); const saving = ref(false); const savingPermissions = ref(false); const keyword = ref(''); const dialogVisible = ref(false); const editingRole = ref<PlatformRole>(); const permissionDialogVisible = ref(false); const permissionRole = ref<PlatformRole>(); const selectedPermissionIds = ref<number[]>([])
const filteredRoles = computed(() => { const value = keyword.value.trim(); return value ? roles.value.filter(item => `${item.name}${item.roleCode}${item.description ?? ''}`.includes(value)) : roles.value })
async function load() { loading.value = true; try { const [roleData, permissionData] = await Promise.all([listPlatformRoles(), listPlatformPermissions()]); roles.value = roleData; permissions.value = permissionData } catch (error) { ElMessage.error(error instanceof Error ? error.message : '平台角色加载失败') } finally { loading.value = false } }
function openCreate() { editingRole.value = undefined; dialogVisible.value = true }
function openEdit(role: PlatformRole) { editingRole.value = role; dialogVisible.value = true }
async function save(command: PlatformRoleCommand) { saving.value = true; try { if (editingRole.value) { const updateCommand: UpdatePlatformRoleCommand = { name: command.name, description: command.description }; await updatePlatformRole(editingRole.value.id, updateCommand) } else await createPlatformRole(command); ElMessage.success('平台角色已保存'); dialogVisible.value = false; await load() } catch (error) { ElMessage.error(error instanceof Error ? error.message : '平台角色保存失败') } finally { saving.value = false } }
async function toggleStatus(role: PlatformRole) { const enabled = role.status !== 'ENABLED'; try { await ElMessageBox.confirm(`确认${enabled ? '启用' : '停用'}“${role.name}”吗？`, '角色状态确认', { type: 'warning' }); await updatePlatformRoleStatus(role.id, enabled); ElMessage.success('角色状态已更新'); await load() } catch (error) { if (error !== 'cancel') ElMessage.error(error instanceof Error ? error.message : '角色状态更新失败') } }
async function managePermissions(role: PlatformRole) { permissionRole.value = role; try { selectedPermissionIds.value = await listPlatformRolePermissionIds(role.id); permissionDialogVisible.value = true } catch (error) { ElMessage.error(error instanceof Error ? error.message : '角色权限加载失败') } }
async function savePermissions(permissionIds: number[]) { if (!permissionRole.value) return; savingPermissions.value = true; try { await replacePlatformRolePermissions(permissionRole.value.id, permissionIds); selectedPermissionIds.value = permissionIds; ElMessage.success('角色权限已保存'); permissionDialogVisible.value = false } catch (error) { ElMessage.error(error instanceof Error ? error.message : '角色权限保存失败') } finally { savingPermissions.value = false } }
onMounted(load)
</script>
