<template>
  <PageHeader title="平台账号" description="维护平台运营账号及所属角色，账号状态和敏感操作由服务端再次鉴权。" eyebrow="权限管理"><template #action><el-button v-if="hasPermission('platform:account:create')" type="primary" @click="openCreate">新增账号</el-button></template></PageHeader>
  <section class="filter-panel"><div class="filter-field filter-keyword"><label>账号名称 / 手机号</label><el-input v-model="keyword" :prefix-icon="Search" clearable placeholder="请输入账号名称或手机号" /></div><div class="filter-field"><label>状态</label><el-select v-model="statusFilter" clearable placeholder="全部状态"><el-option label="已启用" value="ENABLED" /><el-option label="已停用" value="DISABLED" /></el-select></div><div class="filter-field"><label>所属角色</label><el-select v-model="roleFilter" clearable placeholder="全部角色"><el-option v-for="role in roles" :key="role.id" :label="role.name" :value="role.id" /></el-select></div><div class="filter-actions"><el-button @click="resetFilters">重置</el-button><el-button :icon="RefreshCw" :loading="loading" @click="load">刷新</el-button></div></section>
  <section class="content-card"><div class="table-summary">共 <b>{{ filteredAccounts.length }}</b> 条记录</div><el-table v-loading="loading" :data="filteredAccounts" class="data-table" empty-text="暂无平台账号"><el-table-column label="账号名称" min-width="170"><template #default="{ row }"><div class="account-name"><span>{{ row.displayName.slice(0, 1) }}</span><b>{{ row.displayName }}</b></div></template></el-table-column><el-table-column prop="mobile" label="手机号" min-width="150" /><el-table-column label="所属角色" min-width="220"><template #default="{ row }"><el-tag v-for="id in row.roleIds" :key="id" class="role-tag" effect="plain">{{ roleName(id) }}</el-tag></template></el-table-column><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag class="status-tag" :class="row.status === 'ENABLED' ? 'status-enabled' : 'status-disabled'">{{ row.status === 'ENABLED' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="180"><template #default="{ row }">{{ formatTime(row.createdAt) }}</template></el-table-column><el-table-column label="操作" width="220" fixed="right"><template #default="{ row }"><el-button v-if="hasPermission('platform:account:update')" link type="primary" @click="openEdit(row)">编辑</el-button><el-button v-if="hasPermission('platform:account:password:reset')" link @click="resetPassword(row)">重置密码</el-button><el-button v-if="hasPermission('platform:account:status:update')" link :type="row.status === 'ENABLED' ? 'danger' : 'primary'" @click="toggleStatus(row)">{{ row.status === 'ENABLED' ? '停用' : '启用' }}</el-button></template></el-table-column></el-table></section>
  <AccountFormDialog v-model="dialogVisible" :account="editingAccount" :roles="roles" :submitting="saving" @submit="save" />
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessageBox } from 'element-plus'
import { RefreshCw, Search } from 'lucide-vue-next'
import PageHeader from '../../components/common/PageHeader.vue'
import AccountFormDialog from '../../components/business/platform/AccountFormDialog.vue'
import { createPlatformAccount, listPlatformAccounts, listPlatformRoles, resetPlatformAccountPassword, updatePlatformAccount, updatePlatformAccountStatus } from '../../api/platform/access'
import type { CreatePlatformAccountCommand, PlatformAccount, PlatformRole, UpdatePlatformAccountCommand } from '../../types/platform-access'
import { message } from '../../utils/message'
import { useSession } from '../../stores/session'

const accounts = ref<PlatformAccount[]>([]); const roles = ref<PlatformRole[]>([]); const loading = ref(false); const saving = ref(false); const keyword = ref(''); const statusFilter = ref<PlatformAccount['status']>(); const roleFilter = ref<number>(); const dialogVisible = ref(false); const editingAccount = ref<PlatformAccount>()
const hasPermission = useSession().hasPermission
const filteredAccounts = computed(() => accounts.value.filter(item => { const value = keyword.value.trim(); return (!value || `${item.displayName}${item.mobile}`.includes(value)) && (!statusFilter.value || item.status === statusFilter.value) && (!roleFilter.value || item.roleIds.includes(roleFilter.value)) }))
const roleName = (id: number) => roles.value.find(role => role.id === id)?.name ?? `角色 #${id}`
const formatTime = (value: string) => value ? new Intl.DateTimeFormat('zh-CN', { dateStyle: 'medium', timeStyle: 'short', hour12: false }).format(new Date(value)) : '—'
async function load() { loading.value = true; try { const [accountData, roleData] = await Promise.all([listPlatformAccounts(), listPlatformRoles()]); accounts.value = accountData; roles.value = roleData } catch (error) { message.error(error instanceof Error ? error.message : '平台账号加载失败') } finally { loading.value = false } }
function openCreate() { editingAccount.value = undefined; dialogVisible.value = true }
function resetFilters() { keyword.value = ''; statusFilter.value = undefined; roleFilter.value = undefined }
function openEdit(account: PlatformAccount) { editingAccount.value = account; dialogVisible.value = true }
async function save(command: CreatePlatformAccountCommand | UpdatePlatformAccountCommand) { saving.value = true; try { if (editingAccount.value) await updatePlatformAccount(editingAccount.value.id, command as UpdatePlatformAccountCommand); else await createPlatformAccount(command as CreatePlatformAccountCommand); message.success('平台账号已保存'); dialogVisible.value = false; await load() } catch (error) { message.error(error instanceof Error ? error.message : '平台账号保存失败') } finally { saving.value = false } }
async function toggleStatus(account: PlatformAccount) { const enabled = account.status !== 'ENABLED'; try { await ElMessageBox.confirm(`确认${enabled ? '启用' : '停用'}“${account.displayName}”吗？`, '账号状态确认', { type: 'warning' }); await updatePlatformAccountStatus(account.id, enabled); message.success('账号状态已更新'); await load() } catch (error) { if (error !== 'cancel') message.error(error instanceof Error ? error.message : '账号状态更新失败') } }
async function resetPassword(account: PlatformAccount) { try { await ElMessageBox.confirm(`确认按系统安全策略重置“${account.displayName}”的密码吗？原登录状态会立即失效。`, '重置平台账号密码', { type: 'warning' }); const result = await resetPlatformAccountPassword(account.id); if (result.mode === 'RANDOM' && result.temporaryPassword) await ElMessageBox.alert(`本次临时密码：${result.temporaryPassword}\n\n该密码仅展示本次，请立即复制并交给账号使用者。`, '密码已重置', { confirmButtonText: '我已记录' }); else message.success('密码已按固定策略重置，历史登录状态已失效') } catch (error) { if (error !== 'cancel') message.error(error instanceof Error ? error.message : '密码重置失败') } }
onMounted(load)
</script>

<style scoped>.role-tag + .role-tag { margin-left: 6px; }.account-name { display:flex; align-items:center; gap:9px; }.account-name span { display:grid; place-items:center; width:28px; height:28px; border-radius:50%; color:#fff; font-size:11px; font-weight:600; background:linear-gradient(135deg, var(--domain-700), var(--domain-500)); }.account-name b { font-size:13px; font-weight:500; }</style>
